name: Child Workflow - Install Maven

on:
  workflow_run:
    workflows: ["parent.yml"]
    types:
      - completed

jobs:
  install_maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Maven
        run: |
          # Install Maven here

      # Set Maven Output
      - name: Set Maven Output
        id: maven-output
        run: |
          echo "::set-output name=installed::true"

    outputs:
      installed: ${{ steps.maven-output.outputs.installed }}

  notify_parent:
    needs: install_maven
    runs-on: ubuntu-latest
    steps:
      - name: Notify Parent Workflow
        run: |
          echo "Notifying Parent Workflow..."
          curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "child-completed"}'
