name: Child Workflow - Install Maven

on:
  repository_dispatch:
    types: [install-maven]

jobs:
  install_maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Maven
        run: |
          # Install Maven here
          sudo apt update
          sudo apt install maven -y

      - name: Set Maven Output
        id: maven-output
        run: |
          echo "INSTALLED=true" >> $GITHUB_ENV

    outputs:
      installed: ${{ steps.maven-output.outputs.installed }}
