name: Parent Workflow

on: workflow_dispatch

jobs:
  trigger_child_workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Trigger Maven Installation Workflow
        id: trigger
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Personal Access Token with appropriate permissions
          repository: nehafathimaa/t2  # Repository where child workflows are defined
          event-type: install-maven

      - name: Wait for Child Workflows
        run: |
          sleep 10

      - name: Collect Child Workflow Outputs
        id: maven
        run: |
         echo "Installed: ${{ steps.trigger.outputs.installed }}"
        
      - name: Generate Summary Report
        run: |
          echo "Summary Report:"
          echo "Maven Installed: ${{ steps.maven.outputs.installed }}" >> $GITHUB_STEP_SUMMARY
