name: Parent Workflow

on:
  repository_dispatch:
    types: [child-completed]  # Triggered by child workflow when completed

jobs:
  trigger_child_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Trigger Child Workflow
        run: |
          # Trigger the child workflow using repository_dispatch
          echo "Triggering Child Workflow..."
          curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "install-maven"}'

      # Collect child workflow outputs
      - name: Collect Child Workflow Outputs
        run: |
          echo "Child Maven Installed: ${{fromJson(steps.maven.outputs.installed)}}"

      # Generate Summary Report
      - name: Generate Summary Report
        run: |
          echo "Summary Report:"
          echo "Maven Installed: ${{fromJson(steps.maven.outputs.installed)}}" >> $GITHUB_STEP_SUMMARY
